### ISSUE TITLE
Pasting code into custom plugin breaks site. 

### ISSUE THREAD

**Issue by cmarabate** [pods-framework/pods-export-code#3]
The plugin itself seems to work but when I paste the code it gives me into my custom plugin, it breaks my site. I made sure to paste it within the <?php ?> tags. I also made sure to disable the Pods plugin before activating my custom plugin.

Any idea what I'm doing wrong? 

Thanks,

Chris

**Comment by nicdford** [comment]
@cmarabate  since you didn't respond on slack, i thought i'd post here as well. 

[10:49] 
also, after reading your issue on github, i'm like 99% sure you need to have pods activated on the site for it to work

[10:50] 
it doesn't replace the plugin entirely, just lets you setup the CPT and fields programmatically.

**Comment by cmarabate** [comment]
That is disappointing but thanks!

**Comment by sc0ttkclark** [comment]
Sorry, there's just no way to provide the functionality (or even a 10% of it) without having Pods activated, until we get something like the [Fields API](https://github.com/sc0ttkclark/wordpress-fields-api) into WordPress core.

**Comment by cmarabate** [comment]
No problem, does that mean it is something you plan to make possible eventually?

**Comment by sc0ttkclark** [comment]
As soon as Fields API gets slated for a WordPress release, I will personally write an exporter that exports Pods fields into Fields API compatible code -- like within 10 minutes of the decision :)

**Comment by cmarabate** [comment]
Awesome, that is very good to hear! 

Is there a mailing list I can subscribe to that will let me know when it gets released?

Thanks again!

**Comment by sc0ttkclark** [comment]
If you subscribe to the Pods mailing list, you'll get this and other feature announcements coming up. It's on the left side of this page: http://pods.io/forums/

**Comment by cmarabate** [comment]
You're the best, thanks once again! I will leave you alone now =).
